Algoritmo "areacirculo"
// Disciplina   : Lógica de Programação
// Professor    : Jailson Santos
// Descrição    : Calcular a área de um círculo
// Autor(a)     : Sofia
// Data atual   : 29/09/2025

Var
// Seção de Declarações das variáveis
   raio, area : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o raio do círculo: ")
   leia(raio)
   area <- 3.14159 * (raio * raio)
   escreval("Área do círculo = ", area)
   
Fimalgoritmo
