Algoritmo "areaquadrado"
// Disciplina   : Lógica de Programação
// Professor    : Jailson Santos
// Descrição    : Calcular a área de um quadrado
// Autor(a)     : Sofia
// Data atual   : 29/09/2025

Var
   // Seção de Declarações das variáveis
   lado, area : real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o lado do quadrado: ")
   leia(lado)
   area <- lado * lado
   escreval("Área do quadrado = ", area)
   
Fimalgoritmo